version: "3.8"
services:
  admin-panel:
    image: ghcr.io/opexdev/admin-panel
    environment:
      - APP_TITLE=$ADMIN_TITLE
      - DESCRIPTION=$ADMIN_DESCRIPTION
      - API_BASE_URL=$API_BASE_URL
      - FRONT_URL=$FRONT_URL
      - CLIENT_ID=$CLIENT_ID
      - CLIENT_SECRET=$CLIENT_SECRET
      - SUPERSET_URL=$SUPERSET_URL
    networks:
      - default
    deploy:
      restart_policy:
        condition: on-failure
networks:
  default:
    driver: bridge
